### ISSUE TITLE
Parser stops on empty statement ""

### ISSUE THREAD

**Issue by raphaelvoisin** [kodus/sql-split#1]
The parser seems to stop as soon as he reach an empty statement (";;"):

```PHP
<?php

require 'vendor/autoload.php';

$sql = 'SELECT * FROM `table1`;;SELECT * FROM `table2`';

$result = \Kodus\SQL\Splitter::split($sql);

var_dump($result);
```

Output :
```PHP
array(1) {
  [0] =>
  string(22) "SELECT * FROM `table1`"
}
```

Do you think that you can fix this issue ? Do you want me to submit a PR ?

**Comment by mindplay-dk** [comment]
Personally, I would fix my SQL instead, if that's possible.

If you can address this cleanly and without any major changes, you're welcome to submit a PR.

**Comment by raphaelvoisin** [comment]
Hi, I understand your point but I think such library can be used in many use-cases where this will not be the expected behaviour :).
I'll try to submit a MR, thanx for your answer !
